/**
 * Problem 2 - Even Fibonacci numbers
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * Q: By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * A: 4613732
 */
fun main() {
    println("Even Fibonacci numbers ${fib(4000000)}")
}

fun fib(limit: Int): Int {
    var sum = 0
    var a = 1
    var b = 1
    var c = a + b
    while (c < limit) {
        sum += c
        a = b + c
        b = c + a
        c = a + b
    }
    return sum
}

